name: Bug report
description: Create a report to help us improve WinOptimizer
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: os-version
    attributes:
      label: Windows Version
      description: e.g. Windows 11 23H2
      placeholder: Windows 11
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: I ran Module 1 and it gave an error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant logs from C:\WinOptimizer\logs here.
      render: shell
